[package]
name = "tllm"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
copypasta = "0.10.1"
crossterm = "0.27.0"
native-tls = "0.2.12"
serde_json = "1.0.120"
serde = { version = "1.0", features = ["derive"] }
